---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-manager-data
  namespace: nginx-manager
  labels:
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: nginx-manager
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""  # Use default storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-manager-web
  namespace: nginx-manager
  labels:
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: nginx-manager
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""  # Use default storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-manager-ssl
  namespace: nginx-manager
  labels:
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: nginx-manager
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Use default storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-manager-sites
  namespace: nginx-manager
  labels:
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: nginx-manager
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Use default storage class